# Generated by Django 4.1.5 on 2023-01-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='transacted_at',
        ),
    ]
