# Generated by Django 4.1.5 on 2023-01-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_created_at_transaction_transacted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Initialized', max_length=45),
        ),
    ]
